name: pangaea-bench
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy[version='>=1.21,<2.0']
  - pytorch>=2.1
  - einops
  - fastai::opencv-python-headless
  - gdown
  - geopandas
  - google-cloud-storage
  - hydra-core
  - numpy[version='>=1.21,<2.0']
  - omegaconf
  - pillow
  - ptflops
  - pydataverse
  - pytest
  - pytorch-cuda=11.8
  - rasterio
  - rioxarray
  - scikit-learn
  - tensorboard
  - tifffile
  - timm
  - torchaudio
  - torchvision
  - tqdm
  - wandb
  - yacs
  - ipykernel
  - nb_conda_kernels
  - torchmetrics
  - seaborn