train:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        # please refer to the default config for the details of each preprocessor
        - _target_: pangaea.engine.data_preprocessor.RandomCropToEncoder
        # - _target_: pangaea.engine.data_preprocessor.FocusRandomCropToEncoder
        - _target_: pangaea.engine.data_preprocessor.BandFilter
        - _target_: pangaea.engine.data_preprocessor.BandPadding

val:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: pangaea.engine.data_preprocessor.BandFilter
        - _target_: pangaea.engine.data_preprocessor.BandPadding

test:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: pangaea.engine.data_preprocessor.BandFilter
        - _target_: pangaea.engine.data_preprocessor.BandPadding