_target_: pangaea.datasets.landsat_nlcd.Landsat_NLCD
dataset_name: Landsat_NLCD
root_path: /explore/nobackup/people/mfrost2/lscratch/EO_FM/data/Landsat_NLCD
download_url: None
auto_download: False
img_size: 224
#temp: 1
multi_temporal: False
multi_modal: False
ignore_index: -1
num_classes: 20
classes:
     ['Open Water', 
    'Perennial Ice/Snow',
    'Developed, Open Space',
    'Developed, Low Intensity',
    'Developed, Medium Intensity',
    'Developed, High Intensity',
    'Barren Land (Rock/Sand/Clay)',
    'Deciduous Forest',
    'Evergreen Forest',
    'Mixed Forest',
    'Dwarf Scrub',
    'Shrub/Scrub',
    'Grassland/Herbaceous', 
    'Sedge/Herbaceous', 
    'Lichens',
    'Moss', 
    'Pasture/Hay',
    'Cultivated Crops',
    'Woody Wetlands',
    'Emergent Herbaceous Wetlands']
distribution:
  - 1.
bands:
  optical:
  - B1
  - B2
  - B3
  - B4
  - B5
  - B6
  - B7
data_mean:
  optical:
  - 7051
  - 7158
  - 7945
  - 7459
  - 18320
  - 12037
  - 8883
data_std:
  optical:
  - 2825
  - 2879
  - 3233
  - 3094
  - 7538
  - 5040
  - 3773
data_min:
  optical:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
data_max:
  optical:
  - 24802
  - 26519
  - 29409
  - 31624
  - 36468
  - 33144
  - 22000




