_target_: pangaea.datasets.ocean_color.OceanColorDataset
dataset_name: OceanColorDataset
root_path: /explore/nobackup/people/ajkerr1/SatVision/OceanColor/chips/unique_chips/2020172_1155
download_url: None
auto_download: False
img_size: 224
multi_temporal: False
multi_modal: False
ignore_index: -1
num_classes: 1
classes:
  - regression
distribution:
  - 1.
bands:
  optical: [B8, B9, B10, B11, B12, B13] # verify
data_mean:
  optical: [0.485, 0.456, 0.404, 0.404, 0.404, 0.404] # change
data_std:
  optical: [0.485, 0.456, 0.404, 0.404, 0.404, 0.404] # change
data_min:
  optical: [0., 0., 0., 0., 0., 0.] # verify
data_max:
  optical: [32767., 32767., 32767., 32767., 32767., 32767.] # verify

num_inputs: 6
num_targets: 1