train: false
work_dir: ""
seed: 234
use_wandb: false

defaults:
  - task: regression
  - dataset: oceancolorval
  - encoder: prithvi
  - decoder: seg-upernet
  - criterion: mse
  - preprocessing: default
  - _self_ 

# TRAINING
num_workers: 1
batch_size: 8

# EXPERIMENT
use_final_ckpt: false
finetune: false
ckpt_dir: prithvi_8_4_25


